### ISSUE TITLE
Is there a way to make it work with React JSX?

### ISSUE THREAD

**Issue by vinibortoletto** [mvdschee/web-accessibility#44]
Is there a way to make it work with React JSX?

**Comment by mvdschee** [comment]
No, I have it enabled for `*.tsx` and `*.jsx` but as for my current project (react) no issues has been reported and it has to do with you writing not real HTML, React uses `ariaLabel`, `className` etc. which is because the real `aria-label`, `class` are reserved for `<HTMLElements>`. trying `class` on a `div` would result in an error:
```
Type '{ children: Element; class: string; }' is not assignable to type 'DetailedHTMLProps<HTMLAttributes<HTMLElement>, HTMLElement>'.
  Property 'class' does not exist on type 'DetailedHTMLProps<HTMLAttributes<HTMLElement>, HTMLElement>'. Did you mean 'className'?
```
You are writing JS which means it doesn't follow normal HTML rules. 

React has a plugin to help you with some Accessibility issues: [react: development-assistance](https://reactjs.org/docs/accessibility.html#development-assistance) I recommend you use that for the time being.

**Comment by vinibortoletto** [comment]
Thank you! I'll check the React plugin.
